### ISSUE TITLE
there is no documenation for the download process

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#104]
### Tasks 
- [x] Introduction: intention of MaStR-Downloader, ...
- [x] Configuration
- [x] Start download with `main.py`
- [ ] Describe currently in `dev` integrated parallelization options
- [x] Describe scripts involved along structure-diagram
- [x] Mention where data is stored and how files are named

**Comment by gplssm** [comment]
Closed by #105
