### ISSUE TITLE
There are wrongly located entries

### ISSUE THREAD

**Issue by BenPortner** [OpenEnergyPlatform/open-MaStR#12]
Release v1.4 still contains several wrongly located powerplants. I am working to remove these. Current progress can be tracked in my notebook [BenPortner:feature_postprocessing/postprocessing/OEP_MaStR_cleaning.ipynb](https://github.com/BenPortner/open-MaStR/blob/feature_postprocessing/postprocessing/OEP_MaStR_cleaning.ipynb).

**To-do:**
- [X] test if coordinates on German soil
- [X] test if coordinates in German part of Baltic sea
- [X] test if coordinates in German part of North Sea
- [X] check if coordinates are contained in the right Bundesland
- [X] overwrite outlier coordinates using other sources: OPSD (https://open-power-system-data.org/)

**Latest maps:**
- [correctly (?) located including OPSD extracts](https://nbviewer.jupyter.org/github/BenPortner/open-MaStR/blob/feature_postprocessing/postprocessing/output/OEP_3_located_incl_OPSD.html)

~~Currently, there are still some wrongly located windparks in the sea areas which are not identified correctly as outliers. These should be fixed when the Bundesland check is implemented.~~
Update: No more outliers!

<br>

**Note**: Had to name the branch "feature_postprocessing" instead of "feature/postprocessing" because nbviewer cannot handle forward slashes.

**Comment by Bachibouzouk** [comment]
This issue can be closed then? (I see an unticked box)
If in the PR you write "Closes #12", normally merging the PR would automatically close the issue

**Comment by BenPortner** [comment]
> 
> 
> This issue can be closed then? (I see an unticked box)
> If in the PR you write "Closes #12", normally merging the PR would automatically close the issue

I would like to keep it open until most of the outliers are removed, if that is okay for you?

**Comment by Bachibouzouk** [comment]
Yes :)

**Comment by BenPortner** [comment]
Update: Bundesland check now implemented. PR #14

**Comment by BenPortner** [comment]
That should fix it for now! Reopen if any more outliers are found.
