### ISSUE TITLE
introduce package dir "open-mastr" and move modules below 

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#123]
### Tasks

- [x] Create folder `open-mastr` and move modules below
- [x] Change package name in `setup.py`
- [x] Configure package name in `conf.py`, re-run `sphinx-apidoc` and commit files
- [x] Report in CHANGELOG
