### ISSUE TITLE
refactor data download

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#128]
Since the refactoring incorporates larger changes in the entire file structure of `open_mastr/soap_api`, it's divided into several sub-features 

- [x] provide MaStR-API wrapper for a python interface to MaStR-API queries #83 
  - [x] update docs about MaStR-API wrapper as low-level data access (use module docs)
  - [x] allow to store the token in credentials.cfg as well
  - [x] Find right place (i.e. `open_mastr/__init__.py`) for call of project home dir creation and cofig read
  - [x] Configure Travis #132 
- [x] provide bulk downloader for for power generation units #86 
  - [x] make resulting CSV files `_raw.csv` conform with already existing file structure
  - [x] update docs about bulk downloader
- [x] add multithreading option to bulk download
- [ ] ~~include time-blacklist~~ postponed #148
- [x] include check on remaining API requests (max. remaining queries pre day)
- [x] Allow query more than 2,000 units at once (have to hack around `GetGefilterteListeStromErzeuger`)
- [x] Use existing logger with `log = logging.getLogger(__name__)`
- [x] Add missing tests to `MaStRAPI()` #131 
- [x] Remove old download code
- [x] Integrate storages
- [x] Streamline docs #135 
- [ ] ~~Clean raw data~~ postponed #139 
- [x] Report changes in CHANGELOG and write so sentences about refactored code
