### ISSUE TITLE
equip MaStRAPI and credentials with more tests

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#131]
### TODOs
- [x] Test queries from `MaStRAPI.*`
- [x] Test credentials
- [x] Find a way to use credentials from GitHub secrets when tested on Travis
- [x] Note in dev docs that credentials need to be specific for running tests locally
