### ISSUE TITLE
streamline docs

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#135]
### Tasks

- [x] Move README content partially to RTD
- [x] Think about including remaining README into index.rst
- [x] Sort content in sections download, post-processing, analyze with content in getting started
