### ISSUE TITLE
Consider to re-include blacklisted time 

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#148]
Even though recent - even bulk - download tests worked well without interrupting during black listed time frames, it might be a valuable feature to be included in the downloader

Save code
https://github.com/OpenEnergyPlatform/open-MaStR/blob/7a0e5671b39bfa206685fb20f5640e2dba6b3d64/open_mastr/soap_api/utils.py#L18-L41

**Comment by gplssm** [comment]
**Decision:** re-include this feature which slight modifications.

The main expected modification is to control over number of processes for concurrent data retrieval instead on binary decision between download or no download in black-listed times. Then, specifying `processes=0` refers to no download.

### Tasks

- [ ] Find suitable location in code hierarchy that covers all relevant areas of parallelized data download
- [ ] Adapt existing code to new code structure in open-MaStR
- [ ] Implement feature to control over number of processes

**Comment by chrwm** [comment]
Not clear if this feature is still needed or what its purpose is. Re-open if necessary.
