### ISSUE TITLE
Mirror MaStR database by continously querying latest data

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#149]
Because downloading the entire MaStR database from scratch ever time an update is needed takes too long, a continuous updater is required that more or less mirrors the MaStR database. 

This will be implemented using a (dockered) PostgreSQL database access through SQLAlchemy. It is checked for new units or units with updated data which is then pull into the database. In a addition, extended data about the unit is requested for download. The list of extended data requests gets iterated in a subsequent process and data is retrieved.

### Tasks

- [x] Download function for basic unit data
- [x] Basic implementation of extended unit download (prototyping with wind)
- [x] Dump and restore functionality
- [x] ORMs of extended unit data
  - [x] wind
  - [x] solar
  - [x] biomass
  - [x] nuclear
  - [x] combustion
  - [x] hydro
  - [x] gsgk
  - [x] storage
  - [ ] ~consumer~ _postponed to #163 
  - [ ] ~gas_consumer~ _postponed to #163 
  - [ ] ~gas_producer~ _postponed to #163 
  - [ ] ~gas_storage~ _postponed to #163 
- [x] ORMs of eeg unit data
  - [x] wind
  - [x] solar
  - [x] biomass
  - [x] hydro
  - [x] gsgk
  - [x] storage
- [x] ORMs of kwk unit data
  - [x] biomass
  - [x] combustion
  - [x] gsgk
- [ ] ORMs of permit unit data
  - [x] wind
  - [x] solar
  - [x] biomass
  - [x] nuclear
  - [x] combustion
  - [x] hydro
  - [x] gsgk
  - [x] storage
- [x] Configure `backfill_basic()` such that only data with newer timestamp gets inserted, see [here](https://github.com/OpenEnergyPlatform/open-MaStR/blob/9e7ec49fd9f34819d5326d28a808ce15e42c3ec9/open_mastr/soap_api/prototype_mastr_reflected.py#L113-L114)
- [x] Remove data dependent column creation when flattening in [flatten_rule_expand](https://github.com/OpenEnergyPlatform/open-MaStR/blob/3d6ed8663e0072a4ee364a5c8c1c11a07f4cbfb9/open_mastr/soap_api/download.py#L271-L272)
- [ ] ~Re-include adopted time blacklisted that can control number of prcesses used to download additional unit data~ maybe later #148 
- [ ] ~Properly delete successful additional data download requests~ not soo urgent anymore, postponed #154 
- [ ] ~Allow multiprocessing with `basic_unit_data()`~ postponed #161 
- [ ] ~Download only EEG, KWK and permit data for units with "StatistikFlag=='B'". This information is included in extended unit data, see todo note [here](https://github.com/OpenEnergyPlatform/open-MaStR/blob/9e7ec49fd9f34819d5326d28a808ce15e42c3ec9/open_mastr/soap_api/prototype_mastr_reflected.py#L116)~
- [x] Add function to create new additional data requests for units with EegMastrNummer, KwkMastrNummer, and so on and recreate requests after inital backfill was completed
- [ ] Delete additional data requests for units where it failed X times
- [x] Make private methods of `download.py` that are used during mirroring public
- [x] Sort code to desired locations and maybe rename files
- [x] CSV export to `*_raw.csv` compatible format
- [ ] ~Handle NewConnectionError type~ postponed #155
- [x] Write docs and link class
- [x] Add to CHANGELOG
