### ISSUE TITLE
Metadata for raw data

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#160]
Right now, data downloaded wih the refactored code has no metadata, for example columns aren't described. Add metadata adhering to [oemetadata](https://github.com/OpenEnergyPlatform/oemetadata/) schema. 

Additional thoughts

- Consider to use [frictionless Data Package](https://frictionlessdata.io/). Have a look how [pyam](https://pyam-iamc.readthedocs.io/en/stable/api/io.html#the-frictionless-data-package) uses datapackage

### Tasks

- [x] Parse data documentation from MaStR XML file and convert to dict
- [x] Verify all columns for each technology and data type are present in the above
- [x] Replace type `mastr:<special-mastr-type>` are converted to basic types or take these from the data itselfs
- [x] Integrate updated column descriptions into metadata JSONs
- [x] Allow option in `datapackage_meta_json()` to include only a subset of technologies in the resources list (those data gets saved for)
- [x] Validate `datapackage.json` with `frictionless validate`
- [x] Exclude columns that are not exported to CSV
