### ISSUE TITLE
Add filtering by EinheitMastrNummer first 3 characters for duplicates removal

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#180]
This should expects that all raw data including duplicated units (SME and SEE)  are exported by `MaStRMirror.to_csv()`.
Instead of filtering by StatistikFlag A/B, first three characters of `EinheitMastrNummer` are used to distinguish between migrated and newly entered data.

**Tasks**

- [x] Understand _Nummernkonzept_ and define matching regex expression
- [x] Provide function for filtering out SME units
- [ ] ~Test for all technologies like for wind (and provide this as Jupyter Notebook)~ simply not done
- [ ] ~Move description of how data needs to be filtered by A/B from MaStRMirror to static documentation and link to there~ postponed to #182 

That's what Clara did for proofing this filter criterion on wind data:

```python
In[8]: wea.groupby([wea.EinheitMastrNummer.str[:3],
                   wea.StatisikFlag,
                   wea.Inbetriebnahmedatum >= '2019-01-31']).size()
Out[8]: 
EinheitMastrNummer  StatisikFlag  Inbetriebnahmedatum
SEE                 A             False                  29712
                    B             False                    147
                                  True                    1006
SME                 B             False                  29468
                                  True                       2
dtype: int64
```
