### ISSUE TITLE
Update data documentation

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#182]
The [data documentation](https://open-mastr.readthedocs.io/en/dev/data_documentation.html) needs an update. 

**Tasks**

- [ ] Introduce data stages: raw, cleaned and processed
- [ ] Move description of how data needs to be filtered by A/B from MaStRMirror to [data documentation](https://open-mastr.readthedocs.io/en/dev/data_documentation.html) and link to there
- [ ] Add tabular data documentation for processed data

**Comment by chrwm** [comment]
Partly existent in the current documentation.
