### ISSUE TITLE
LICENSE file for Zenodo upload missing in repo

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#186]
**Tasks**

- [x] Include LICENSE file in repo
- [x] Add to package_data to include in `site_package`
- [x] Amend CHANGELOG about Zenodo upload
