### ISSUE TITLE
Mastr csv export is failing due to wrong PLZ values

### ISSUE THREAD

**Issue by deniztepe** [OpenEnergyPlatform/open-MaStR#319]
CSV export with the current version 0.11.4 failing with the following error traceback. The bulk data origins from 10.08.2022.

<details>
<summary>Error traceback</summary>

```
Traceback (most recent call last):
  File "C:\Users\deniz\Documents\open-MaStR\open_mastr\mastr_download_deniztest.py", line 71, in <module>
    mastr.to_csv()
  File "C:\Users\deniz\Documents\open-MaStR\open_mastr\mastr.py", line 326, in to_csv
    df = pd.read_sql(table, con=self._engine)
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\io\sql.py", line 583, in read_sql
    return pandas_sql.read_table(
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\io\sql.py", line 1457, in read_table
    return table.read(
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\io\sql.py", line 1017, in read
    self._harmonize_columns(parse_dates=parse_dates)
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\io\sql.py", line 1148, in _harmonize_columns
    self.frame[col_name] = df_col.astype(col_type, copy=False)
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\core\generic.py", line 5920, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\core\internals\managers.py", line 419, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\core\internals\managers.py", line 304, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\core\internals\blocks.py", line 580, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\core\dtypes\cast.py", line 1292, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\core\dtypes\cast.py", line 1237, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "C:\Users\deniz\Anaconda3\envs\fortiss\lib\site-packages\pandas\core\dtypes\cast.py", line 1154, in astype_nansafe
    return lib.astype_intsafe(arr, dtype)
  File "pandas\_libs\lib.pyx", line 668, in pandas._libs.lib.astype_intsafe
ValueError: invalid literal for int() with base 10: 'A-6794'
```

</details>

Some possible explanations that I came across are:
* Postleitzahl column in electricity_consumer table are of type integer and are not properly pre-processed (5-digit strings on general).
* Accordingly the read_sql function doesn't work assuming the column is integer. 
* The reason that the error only got realized now, maybe  that irregular PLZ 'A-6794' occurs only twice at quite current entries. 

## TODO

- [x] Check column datatypes for PLZ at all tables -> ORM changes
- [x] Check that PLZ pre-proccessing covers all tables
- [x] Test to_csv with current mastr for all tables.
- [x] Mind compatibility with parallel issues ( #269, #314, #316, #317)
