### ISSUE TITLE
Submit open-mastr paper to joss

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#462]
For a paper submission, we need to do the following:

- [x] Create a branch containing a `paper.md` file
- [x] Release v0.14.0
- [x] Update the documentation to mkdocs
- [x] Conduct an own review of `open-mastr`, following the checklist described [here](https://joss.readthedocs.io/en/latest/review_checklist.html)
- [x] Run the whole `paper.md` file through a spell checker
- [x] Get permission from all authors to submit paper

## Tasks within the paper

- [x] Add orcids of all authors
- [x] Add affiliation of all authors

**Comment by FlorianK13** [comment]
Paper is submitted - search for editors and reviewers has started, see https://github.com/openjournals/joss-reviews/issues/6199#issuecomment-1884016695
