### ISSUE TITLE
Automate Zenodo data upload

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/open-MaStR#559]
Automate [Zenodo dataset](https://doi.org/10.5281/zenodo.6807425) upload for publishing on a regular basis.
This has been a feature before: #185

**Content**
- [ ] Data files
- [ ] License
- [ ] Datapackage json (check out #386)

**Automation steps**
- [ ] Download latest data
- [ ] Basic validation of data integrity to catch errors like #547 #548, do not proceed on error
- [ ] Create datapackage
- [ ] Zip and upload to Zenodo (see also #558)

**Operational**
- [ ] Frequency, month or quarter?
- [ ] Create cronjob
- [ ] Push status to telegram group

Feel free to amend @FlorianK13

**Comment by FlorianK13** [comment]
By automating the zenodo upload we could also solve #558

**Comment by nesnoj** [comment]
Maybe auto-dl more regular to build up archive, check plausiblity/integrity and eventually add issue on error

**Comment by fneum** [comment]
This would be very cool, especially since the last Zenodo release was released in August 2023. Perhaps you could squeeze in a manual release soon-ish?

**Comment by nesnoj** [comment]
> This would be very cool, especially since the last Zenodo release was released in August 2023. Perhaps you could squeeze in a manual release soon-ish?

Yes, I will

**Comment by nesnoj** [comment]
> This would be very cool, especially since the last Zenodo release was released in August 2023. Perhaps you could squeeze in a manual release soon-ish?

Sorry for taking so long @fneum , new release is out now: https://zenodo.org/records/14783581
Also an unboxed version with individually zipped CSVs: https://zenodo.org/records/14843222
